USE [master]
GO
/****** Object:  Database [eCommerceDb]    Script Date: 10.08.2021 17:59:56 ******/
CREATE DATABASE [eCommerceDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eCommerceDb', FILENAME = N'C:\Users\kkurc\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\eCommerceDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eCommerceDb_log', FILENAME = N'C:\Users\kkurc\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\eCommerceDb.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [eCommerceDb] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eCommerceDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [eCommerceDb] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [eCommerceDb] SET ANSI_NULLS ON 
GO
ALTER DATABASE [eCommerceDb] SET ANSI_PADDING ON 
GO
ALTER DATABASE [eCommerceDb] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [eCommerceDb] SET ARITHABORT ON 
GO
ALTER DATABASE [eCommerceDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [eCommerceDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [eCommerceDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [eCommerceDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [eCommerceDb] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [eCommerceDb] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [eCommerceDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [eCommerceDb] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [eCommerceDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [eCommerceDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [eCommerceDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [eCommerceDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [eCommerceDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [eCommerceDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [eCommerceDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [eCommerceDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [eCommerceDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [eCommerceDb] SET RECOVERY FULL 
GO
ALTER DATABASE [eCommerceDb] SET  MULTI_USER 
GO
ALTER DATABASE [eCommerceDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [eCommerceDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [eCommerceDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [eCommerceDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [eCommerceDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [eCommerceDb] SET QUERY_STORE = OFF
GO
USE [eCommerceDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [eCommerceDb]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 10.08.2021 17:59:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Category] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 10.08.2021 17:59:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Products] ON 
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (1, N'Ice Cream', N'Snack')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (2, N'Chocolate', N'Snack')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (3, N'Tshirt', N'Outfit')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (4, N'Sweatshirt', N'Outfit')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (5, N'Battery', N'Electronics')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (7, N'Phone', N'Electronics')
GO
INSERT [dbo].[Products] ([Id], [Name], [Category]) VALUES (8, N'Biscuit', N'Snack')
GO
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([Id], [Username], [Password]) VALUES (1, N'kaan', N'123')
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
USE [master]
GO
ALTER DATABASE [eCommerceDb] SET  READ_WRITE 
GO
